-- Experiences Table
create table public.experiences (
  id bigint generated by default as identity primary key,
  query text not null,
  strategy text not null,
  confidence float,
  answer text,
  reason text,
  feedback integer, -- 1 for helpful, 0 for not helpful
  timestamp timestamptz not null default now(),
  features jsonb
);

-- Strategy Performance Table
create table public.strategy_performance (
  strategy text primary key,
  total_uses integer default 0,
  successful_uses integer default 0,
  avg_confidence float default 0.0,
  last_updated timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table public.experiences enable row level security;
alter table public.strategy_performance enable row level security;

-- Create policies to allow anonymous access (for this demo/dev environment)
-- WARN: In production, you'd want strictly authenticated policies.
create policy "Allow generic read access" on public.experiences for select using (true);
create policy "Allow generic insert access" on public.experiences for insert with check (true);
create policy "Allow generic update access" on public.experiences for update using (true);

create policy "Allow generic read access" on public.strategy_performance for select using (true);
create policy "Allow generic insert access" on public.strategy_performance for insert with check (true);
create policy "Allow generic update access" on public.strategy_performance for update using (true);
